C_dl: 10.0
D_o: 3.7e-10
D_r: 3.7e-10
Eo_electrode: -0.18
Eo_redoxcouple: -0.25
F: 96485.332
MHC_prefactor: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/prefactor/pref_data/pref_sc_4.6.mat
c_KCl: 100
c_ruhex: 10
d_h: 5.0e-10
dos_file: /ocean/projects/cts180021p/mbabar/PhD/tBLG_Carr/kp_tblg/MATLAB_vers/TBG_data_nr_48/ldos-th_4.6_nsamps_48_knum_24.mat
e: 1.60218e-19
eps: 80
eps0: 8.854187e-12
iv_file: iv_data.txt
kbT: 0.0259
lambda: 0.82
mesh_file: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/Mesh/Testing/mesh_10.xml
rate_file: eta_run_script.jl
rate_loc: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/k_data_nr_48/4.6/k_data_Vapp_-0.5.mat
sol_dir: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/Current_map/10nm/10mM_Ru3+/eta_-0.5/4.6
sol_file: sol
z_1: 1
z_2: -1
z_3: 3
z_4: 2
