C_dl: 10.0
D_o: 8.43e-10
D_r: 1.19e-09
Eo_electrode: -0.18
Eo_redoxcouple: -0.25
F: 96485.332
MHC_prefactor: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/prefactor/pref_data/pref_sc_4.6.mat
c_KCl: 100
c_ruhex: 2
d_h: 5.0e-10
domain: AB
dos_file: /ocean/projects/cts180021p/mbabar/PhD/tBLG_Carr/kp_tblg/MATLAB_vers/TBG_data_nr_48/ldos-th_4.6_nsamps_48_knum_24.mat
e: 1.60218e-19
eps: 80
eps0: 8.854187e-12
iv_file: iv_data.txt
kbT: 0.0259
lambda: 0.82
mesh_file: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/Mesh/Testing/mesh_5.xml
rate_file: eta_run_script.jl
rate_loc: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/k_data_nr_48/4.6/k_data_Vapp_0.2.mat
sol_dir: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/CV/5nm/2mM/Diff_ruhex/4.6
sol_file: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/CV/5nm/2mM/Diff_ruhex/4.6/config_th_4.6_Vapp_0.2_AB
z_1: 1
z_2: -1
z_3: 3
z_4: 2
