C_dl: 10.0
D_o: 3.7e-10
D_r: 3.7e-10
Eo_electrode: -0.18
Eo_redoxcouple: -0.25
F: 96485.332
MHC_prefactor: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/prefactor/pref_data/pref_sc_1.4.mat
c_KCl: 100
c_ruhex: 2
d_h: 5.0e-10
dos_file: /ocean/projects/cts180021p/mbabar/PhD/tBLG_Carr/kp_tblg/MATLAB_vers/TBG_data_nr_48/ldos-th_1.4_nsamps_48_knum_24.mat
e: 1.60218e-19
eps: 80
eps0: 8.854187e-12
iv_file: iv_data.txt
kbT: 0.0259
lambda: 0.82
mesh_file: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/Mesh/Testing/mesh_5.xml
rate_file: eta_run_script.jl
rate_loc: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/k_data_nr_48/1.4/k_data_Vapp_0.0.mat
sol_dir: /ocean/projects/cts180021p/mbabar/PhD/PDE/PNP_solve/3D_vmg/ldos_incorp/Current_map/5nm/eta_0.0/1.4
sol_file: sol
z_1: 1
z_2: -1
z_3: 3
z_4: 2
